name: CI
on: [push]
jobs:
  setvars:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ steps.vars.outputs.push }}
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set release vars
        id: vars
        run: |
          if [[ "${{ github.ref }}" == 'refs/tags/'* ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
            echo "push=false" >> $GITHUB_OUTPUT
          fi
  validate:
    needs: [setvars]
    uses: ./.github/workflows/validate.yaml
    with:
      tag: ${{ needs.setvars.outputs.tag }}

  cd:
    needs: [ setvars, validate ]
    uses: ./.github/workflows/cd.yaml
    with:
      tag: ${{ needs.setvars.outputs.tag }}
      push: ${{ needs.setvars.outputs.push }}