name: Build, Test, and Publish to PyPI

on:
  push:
    branches:
      - master
    tags: # to publish releases based on tags
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or specify a version like '3.9'
          cache: 'pip'

      - name: Create virtual environment
        run: make venv

      - name: Install dependencies
        run: make deps

      - name: Install package
        run: make install

      - name: Run tests
        run: make test

  publish-to-pypi:
    needs: build-and-test # this job depends on the success of the previous job
    if: startsWith(github.ref, 'refs/tags/') # only runs on tags
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create virtual environment
        run: make venv

      - name: Install dependencies
        run: make deps

      - name: Install build and setuptools
        run: make build

      - name: Build package
        run: make build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi@v1
        with:
          token: ${{ secrets.PYPI_API_TOKEN }}
          # Optional: Specify the repository (testpypi or pypi)
          repository-url: https://upload.pypi.org/legacy/ # or https://test.pypi.org/legacy/ for test pypi